version: '3.7'

services:

  php-apache:
    container_name: api-php-symfony
    ports:
      - 8090:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/app/
      - APACHE_LOG_DIR=/var/www/html/app/var/log
    build: .
    volumes:
      - ./:/var/www/html
      - ./config/vhost.conf:/etc/apache2/sites-available/-default.conf
      - ./app/var/cache:/var/www/html/app/var/cache
      - ./app/var/log:/var/www/html/app/var/log
      - ./app/vendor:/var/www/html/app/vendor
      - ./app/.env:/var/www/html/app/.env
    networks:
        - app-network
    depends_on:
      - app-mysql

  app-mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./docker/volumes/mysql:/var/lib/mysql
      restart: always
      environment:
        MYSQL_DATABASE: "api"
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_USER: "api"
        MYSQL_USER_PASSWORD: "api"
      ports:
        - 3310:3306
      networks:
        - app-network

  app-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge